(function(){
  if(window.__ATENDEBOT360_LOADED__) return;
  window.__ATENDEBOT360_LOADED__=true;
  var script=document.currentScript;
  var d=script?script.dataset:{};
  var business=d.business||'Atendimento';
  var whatsapp=(d.whatsapp||'').replace(/\D/g,'');
  var color=d.color||'#5b5cf0';
  var host=document.createElement('div');
  host.id='at360-widget-host';
  host.innerHTML='<button id="at360-launch" aria-label="Abrir atendimento">💬</button><section id="at360-box" aria-live="polite"><header><div><b>'+esc(business)+'</b><small>● online agora</small></div><button id="at360-close" aria-label="Fechar">×</button></header><main id="at360-body"><div class="at360-msg bot">Olá! 👋 Sou o assistente virtual da '+esc(business)+'. Como posso ajudar?</div></main><div class="at360-quick"><button data-action="info">Informações</button><button data-action="orcamento">Orçamento</button><button data-action="whatsapp">WhatsApp</button></div><form id="at360-form"><input id="at360-input" placeholder="Digite sua mensagem..." autocomplete="off"><button>➜</button></form><footer>Atendimento com AtendeBot 360</footer></section>';
  var style=document.createElement('style');
  style.textContent='#at360-widget-host{font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;position:fixed;right:20px;bottom:20px;z-index:2147483000}#at360-launch{width:58px;height:58px;border:0;border-radius:18px;background:'+color+';color:#fff;font-size:23px;box-shadow:0 14px 38px rgba(15,23,42,.28);cursor:pointer}#at360-box{position:absolute;right:0;bottom:70px;width:350px;max-width:calc(100vw - 28px);height:500px;max-height:calc(100vh - 105px);display:none;flex-direction:column;background:#fff;border:1px solid #e2e8f0;border-radius:20px;overflow:hidden;box-shadow:0 25px 80px rgba(15,23,42,.25);color:#0f172a}#at360-box.open{display:flex}#at360-box header{padding:14px 15px;background:#0f172a;color:#fff;display:flex;justify-content:space-between;align-items:center}#at360-box header b{font-size:13px}#at360-box header small{display:block;color:#86efac;font-size:10px;margin-top:2px}#at360-close{border:0;background:#1e293b;color:#fff;width:30px;height:30px;border-radius:8px;cursor:pointer}#at360-body{flex:1;padding:14px;background:#f8fafc;overflow:auto}.at360-msg{max-width:88%;padding:10px 11px;border-radius:13px;margin-bottom:9px;font-size:12px;line-height:1.45}.at360-msg.bot{background:#fff;border:1px solid #e2e8f0}.at360-msg.user{margin-left:auto;background:'+color+';color:#fff}.at360-quick{display:flex;gap:6px;flex-wrap:wrap;padding:9px;border-top:1px solid #e2e8f0}.at360-quick button{border:1px solid #c7d2fe;background:#eef2ff;color:#4338ca;border-radius:999px;padding:7px 9px;font-size:10px;font-weight:800;cursor:pointer}#at360-form{display:flex;gap:7px;padding:9px;border-top:1px solid #e2e8f0}#at360-input{flex:1;min-width:0;border:1px solid #e2e8f0;border-radius:10px;padding:9px;font:inherit;font-size:12px}#at360-form button{border:0;background:'+color+';color:#fff;border-radius:10px;padding:0 13px;font-weight:800;cursor:pointer}#at360-box footer{text-align:center;padding:6px;color:#94a3b8;font-size:9px;background:#fff}@media(max-width:600px){#at360-widget-host{right:14px;bottom:14px}#at360-launch{width:54px;height:54px}#at360-box{height:68vh}}';
  document.head.appendChild(style);
  document.body.appendChild(host);
  var box=document.getElementById('at360-box'),body=document.getElementById('at360-body'),input=document.getElementById('at360-input');
  document.getElementById('at360-launch').onclick=function(){box.classList.toggle('open')};
  document.getElementById('at360-close').onclick=function(){box.classList.remove('open')};
  function esc(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function add(t,type){var el=document.createElement('div');el.className='at360-msg '+type;el.textContent=t;body.appendChild(el);body.scrollTop=body.scrollHeight}
  function openWA(source){if(!whatsapp){add('O WhatsApp ainda não foi configurado pelo estabelecimento.','bot');return}var msg=encodeURIComponent('Olá! Vim pelo atendimento online da '+business+' e gostaria de mais informações'+(source?' sobre '+source:'')+'.');window.open('https://wa.me/'+whatsapp+'?text='+msg,'_blank')}
  function reply(t){var q=t.toLowerCase();if(q.indexOf('whats')>-1||q.indexOf('atendente')>-1){openWA('meu atendimento');return 'Vou abrir o WhatsApp para você.'}if(q.indexOf('orçamento')>-1||q.indexOf('orcamento')>-1||q.indexOf('preço')>-1||q.indexOf('preco')>-1||q.indexOf('valor')>-1){return 'Posso encaminhar seu pedido para a equipe. Toque em WhatsApp para continuar e receber valores.'}return 'Posso ajudar com informações, orçamento ou encaminhar você para o WhatsApp da equipe.'}
  host.querySelector('.at360-quick').onclick=function(e){var b=e.target.closest('button');if(!b)return;var a=b.dataset.action;if(a==='whatsapp'){add('Falar no WhatsApp','user');openWA('meu atendimento');setTimeout(function(){add('Abrindo o WhatsApp para continuar o atendimento.','bot')},120);return}var txt=a==='orcamento'?'Quero um orçamento':'Quero informações';add(txt,'user');setTimeout(function(){add(reply(txt),'bot')},120)};
  document.getElementById('at360-form').onsubmit=function(e){e.preventDefault();var t=input.value.trim();if(!t)return;input.value='';add(t,'user');setTimeout(function(){add(reply(t),'bot')},120)};
})();